### ISSUE TITLE
direct method access to workers not working on linux

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/blitz.js#19]
tested on ubuntu 16.04.

```
0|index    | /var/www/live/warframe-nexus/node_modules/blitz-js-api/index.js:49
0|index    |         this.server.use(route, fn, "GET")
0|index    |                    ^
0|index    |
0|index    | TypeError: Cannot read property 'use' of undefined
0|index    |     at api.get (/var/www/live/warframe-nexus/node_modules/blitz-js-api/index.js:49:20)
0|index    |     at process.on.msg (/var/www/live/warframe-nexus/node_modules/blitz-js-util/index.js:44:44)
0|index    |     at emitTwo (events.js:106:13)
0|index    |     at process.emit (events.js:194:7)
0|index    |     at process.nextTick (internal/child_process.js:766:12)
0|index    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|index    |     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by Kaptard** [comment]
Likely caused by race condition in blitz.js-util where the function call would arrive before setting the global config.
